### ISSUE TITLE
a question on to_switch_off = [32, 16, 8]

### ISSUE THREAD

**Issue by kkdhc** [db-tu-dresden/FASTgres-PVLDBv16#2]
I have a qusetions on list to_switch_off = [32, 16, 8]. the element in to_switch_off is 32，16，8，can you tell me the
reason? It representative FASTgres𝑐𝑜𝑎𝑟𝑠，FASTgres𝑡𝑎𝑏𝑙，FASTgres𝑓𝑖𝑛𝑒  ？If not，can you tell me why？

**Comment by KiraThiessat** [comment]
Hey there, thanks for interest in our project! With `to_switch_off` you probably mean the list `generate_labels.py` script. This script is used to build the necessary labels for FASTgres to be trained upon. `to_switch_off ` specifically, is an option that allows us to restrict to three hints only, which can be used to generate labels on a coarser level.

This script is not related to the presented approaches of _coarse, table, and fine_. These components are reflected in `query.py` and `context_heuristic.py`, even though we tested only on the finest approach _fine_ using the implementation provided in `query.py`.

**Comment by kkdhc** [comment]
Tanks for you reponse，it is  a great project !  If i want ，i can replace 32，16，8，into the other three bumbers ,such as 1，2,3？

**Comment by KiraThiessat** [comment]
The hint representation follows one hot encoding. When you consider six hints, each hint has the binary form, e.g., [0, 1, 0, 0, 0, 0]. So each hint has a decimal representation that corresponds to 2^i, e.g., [1, 0, 0, 0, 0, 0] -> 2^0 = 1 and so on. You can change those numbers to any exponent of 2^i where i is between 0 and 5. The available options are thus: 1, 2, 4, 8, 16, 32.

Something like 3 does not work, because it is [1, 1, 0, 0, 0, 0] which is a set of hints rather than just one hint. For labeling, we specify only hints to consider. The algorithm tries each combination of the chosen hints.

For this example, you can also choose more or less than three values. If you choose all six hints, this is similar to no restriction at all. If you choose something like: 1, 32 -> only two hints are considered. Thus the search space for each query is 4 combinations.

I hope this helps!
